# Generated by Django 5.1.2 on 2024-11-01 01:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("xy_django_app_information", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MApiAuthCredential",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "app_key",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="app_key",
                    ),
                ),
                (
                    "app_secret",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="app_secret",
                    ),
                ),
                (
                    "versions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(app_label)s_%(class)s_versions",
                        to="xy_django_app_information.mversion",
                        verbose_name="所属版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "授权用户凭证",
                "verbose_name_plural": "授权用户凭证",
            },
        ),
        migrations.CreateModel(
            name="MApiAuthCredentialCache",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("url", models.TextField(blank=True, null=True, verbose_name="名称")),
                (
                    "time_stamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "nonce",
                    models.TextField(blank=True, null=True, verbose_name="nonce标识码"),
                ),
                (
                    "sign",
                    models.TextField(blank=True, null=True, verbose_name="sign标识码"),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_credential",
                        to="ApiAuth.mapiauthcredential",
                        verbose_name="凭证",
                    ),
                ),
            ],
            options={
                "verbose_name": "授权用户凭证缓存",
                "verbose_name_plural": "授权用户凭证缓存",
            },
        ),
    ]
