# Generated by Django 5.1.2 on 2024-10-31 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Demo", "0003_mdemo_region"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mdemo",
            old_name="region",
            new_name="image",
        ),
    ]
